#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: [GET]
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: defaults/homepage.html.twig
        _locale: '%locale%'
